#!/usr/bin/env bash
# Transfering a script from a file to a server
if [ $# -eq 4 ]
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
	Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
fi	
