#!/usr/bin/env bash
# Installing nginx web server
sudo apt-get -y update
#Installs the nginx server
sudo apt-get -y install nginx
#Overwrites the existing default index.html with string hello world
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
# location block for redirection
redirection_location="location \/redirect_me { rewrite ^ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4? permanent; }"
# using sed to configure your Nginx server so that /redirect_me is redirecting to another page.
sudo sed -i "/server_name _/a $redirection_location" /etc/nginx/sites-available/default
# Restarts the server
sudo service nginx restart
