#!/usr/bin/env bash
# updating packages
apt-get -y update

# Getting the nginx server
apt-get -y install nginx

#Overwrites the existing default index.html with string hello world
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# directory to handle error
sudo mkdir /var/www/error

#error message to be displayed
echo "Ceci n'est pas une page" > /var/www/error/404.html

# location block for redirection
sed -i '/server_name _/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
# Configure Nginx for custom 404 page
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default

# Restarts the server
sudo service nginx restart
