#!/usr/bin/env bash
# This script displays message infinitely, sleeps and displays a message
# when SIGTERM signal is received
trap 'echo "I am invincible!!!"' 15
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
