#!/usr/bin/env bash
# This scripts prints from 1 to 100 displaying messages alongside
i=1
while ((i<=100))
do
	if ((i%3 == 0)) && ((i%5 == 0))
	then
		echo "FizzBuzz"
	elif ((i%3 == 0))
	then
		echo "Fizz"
	elif ((i%5 == 0))
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
