#!/usr/bin/env bash
# This script displays number 1 to 20
numbers=1
while ((numbers<21))
do
	echo $numbers
	case $numbers in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
	esac
	((numbers++))
done
