#!/usr/bin/env bash
# you will need to get Apache to run on the container and
# to return a page containing Hello Holberton when querying the root of it
if ! pgrep apache2 > /dev/null; then
	sudo service apache2 start
fi
